question_data = [
    {"type": "multiple", "difficulty": "easy", "category": "Geography",
     "question": "What is the name of the peninsula containing Spain and Portugal?",
     "correct_answer": "Iberian Peninsula",
     "incorrect_answers": ["European Peninsula", "Peloponnesian Peninsula",
                           "Scandinavian Peninsula"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
     "question": "What is the Portuguese word for &quot;Brazil&quot;?",
     "correct_answer": "Brasil",
     "incorrect_answers": ["Brazil", "Brasilia", "Bras&iacute;l"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "The &quot;Day of Defeat&quot; series of games take place during which war?",
     "correct_answer": "World War II",
     "incorrect_answers": ["World War I", "Vietnam War", "Iraq War"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Which band released songs suchs as &quot;Rio&quot;, &quot;Girls on Film&quot;, and &quot;The Reflex&quot;?",
     "correct_answer": "Duran Duran",
     "incorrect_answers": ["The Cure", "New Order", "Depeche Mode"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
     "question": "The medial meniscus forms which part of what joint in the human body?",
     "correct_answer": "Knee", "incorrect_answers": ["Elbow", "Ankle", "Shoulder"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "Who voiced the character Draco in the 1996 movie &#039;DragonHeart&#039;?",
     "correct_answer": "Sean Connery",
     "incorrect_answers": ["Dennis Quaid", "Pete Postlethwaite", "Brian Thompson"]},
    {"type": "multiple", "difficulty": "hard", "category": "Science: Gadgets",
     "question": "Who built the first laser?",
     "correct_answer": "Theodore Harold Maiman",
     "incorrect_answers": ["Nikola Tesla", "Jack Kilby", "Edith Clarke"]},
    {"type": "multiple", "difficulty": "hard", "category": "General Knowledge",
     "question": "If someone said &quot;you are olid&quot;, what would they mean?",
     "correct_answer": "You smell extremely unpleasant.",
     "incorrect_answers": ["You are out of shape\/weak.",
                           "Your appearance is repulsive.",
                           "You are incomprehensible\/an idiot."]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Who had hits in the 70s with the songs &quot;Lonely Boy&quot; and &quot;Never Let Her Slip Away&quot;?",
     "correct_answer": "Andrew Gold",
     "incorrect_answers": ["Elton John", "Leo Sayer", "Barry White "]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "In &quot;Call Of Duty: Zombies&quot;, what is the name of the machine that upgrades weapons?",
     "correct_answer": "Pack-A-Punch",
     "incorrect_answers": ["Wunderfizz", "Gersch Device", "Mule Kick"]}]
